const recentCustomers = [
  {
    id: 1,
    name: "Carol Jenkins",
    date: "05/01/2025",
    age: 56,
    gender: "Female",
    contact: "9933660022",
    bookingType: "Online",
    bookingId: "TID040",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 3,500",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Stargazing",
    time: "7:30 PM",
    cancellationReason: "",
  },
  {
    id: 2,
    name: "Juan Dela Cruz",
    date: "05/01/2025",
    age: 28,
    gender: "Male",
    contact: "9123456789",
    bookingType: "Online",
    bookingId: "TID076",
    addons: "Handwritten Gift",
    paymentMethod: "GCash",
    amountPaid: "PHP 4,500",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "SunsetDate",
    time: "5:00 PM",
    cancellationReason: "",
  },
  {
    id: 3,
    name: "Adam Hall",
    date: "10/01/2025",
    age: 60,
    gender: "Male",
    contact: "1122334455",
    bookingType: "Online",
    bookingId: "TID004",
    addons: "Breakfast",
    paymentMethod: "Cash",
    amountPaid: "PHP 5,950",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Camping",
    time: "2:00 PM",
    cancellationReason: "",
  },
  {
    id: 4,
    name: "Maria Santos",
    date: "10/01/2025",
    age: 25,
    gender: "Female",
    contact: "9987654321",
    bookingType: "Online",
    bookingId: "OID077",
    addons: "Parking",
    paymentMethod: "",
    amountPaid: "PHP 2,200",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Picnics",
    time: "3:30 PM",
    cancellationReason: "",
  },
  {
    id: 5,
    name: "Connor Moore",
    date: "15/01/2025",
    age: 24,
    gender: "Female",
    contact: "55883344",
    bookingType: "Online",
    bookingId: "OID052",
    addons: "Parking",
    paymentMethod: "Cash",
    amountPaid: "PHP 630",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Retro",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 6,
    name: "Ashley Diaz",
    date: "18/01/2025",
    age: 57,
    gender: "Female",
    contact: "8811447700",
    bookingType: "Online",
    bookingId: "OID028",
    addons: "Extra Bed",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,150",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Mystery Hunt",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 7,
    name: "Ella Richardson",
    date: "20/01/2025",
    age: 48,
    gender: "Female",
    contact: "6633880022",
    bookingType: "Online",
    bookingId: "OID064",
    addons: "",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,000",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Coordinated",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 8,
    name: "Allison White",
    date: "25/01/2025",
    age: 31,
    gender: "Female",
    contact: "7799113355",
    bookingType: "Online",
    bookingId: "OID016",
    addons: "Massage",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,400",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Retro",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 9,
    name: "Charles Kelley",
    date: "01/02/2025",
    age: 22,
    gender: "Male",
    contact: "1166994400",
    bookingType: "Online",
    bookingId: "OID043",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 920",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Picnics",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 10,
    name: "Aiden Lee",
    date: "05/02/2025",
    age: 38,
    gender: "Male",
    contact: "6677889900",
    bookingType: "Online",
    bookingId: "OID007",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 700",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Retro",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 11,
    name: "David Morphy",
    date: "08/02/2025",
    age: 37,
    gender: "Male",
    contact: "2288116633",
    bookingType: "Online",
    bookingId: "OID055",
    addons: "Dinner",
    paymentMethod: "Card",
    amountPaid: "PHP 1,780",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Mystery Hunt",
    time: "10:30 AM",
    cancellationReason: "",
  },
  {
    id: 12,
    name: "Emma Rodriguez",
    date: "12/02/2025",
    age: 23,
    gender: "Male",
    contact: "3300557744",
    bookingType: "Online",
    bookingId: "OID067",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 710",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "05/15/2025",
    experience: "Retro",
    time: "10:30 AM",
    cancellationReason: "",
  },

  {
    id: 13,
    name: "Angelo Reyes",
    date: "15/02/2025",
    age: 30,
    gender: "Male",
    contact: "9112233445",
    bookingType: "Walk-in",
    bookingId: "WID078",
    addons: "Transport Rental",
    paymentMethod: "GCash",
    amountPaid: "PHP 3,000",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 14,
    name: "Amy Allen",
    date: "18/02/2025",
    age: 62,
    gender: "Male",
    contact: "4466880022",
    bookingType: "Online",
    bookingId: "OID019",
    addons: "City Tour",
    paymentMethod: "Card",
    amountPaid: "PHP 1,900",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 15,
    name: "Avery Foster",
    date: "25/02/2025",
    age: 39,
    gender: "Male",
    contact: "5588114477",
    bookingType: "Online",
    bookingId: "OID031",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 630",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 16,
    name: "Eleanor Powell",
    date: "01/03/2025",
    age: 29,
    gender: "Male",
    contact: "5511449966",
    bookingType: "Online",
    bookingId: "OID061",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 690",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 17,
    name: "Trisha Gomez",
    date: "02/03/2025",
    age: 27,
    gender: "Female",
    contact: "9234567890",
    bookingType: "Online",
    bookingId: "OID079",
    addons: "Photographer, Car Rental",
    paymentMethod: "Maya",
    amountPaid: "PHP 3,500",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 18,
    name: "Anthony Cook",
    date: "05/03/2025",
    age: 26,
    gender: "Male",
    contact: "2255881144",
    bookingType: "Online",
    bookingId: "OID025",
    addons: "Dinner",
    paymentMethod: "Card",
    amountPaid: "PHP 1,700",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 19,
    name: "Cameron Howard",
    date: "10/03/2025",
    age: 28,
    gender: "Male",
    contact: "3377004466",
    bookingType: "Online",
    bookingId: "OID037",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 780",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 20,
    name: "Aaliyah Brown",
    date: "15/03/2025",
    age: 32,
    gender: "Female",
    contact: "9876543210",
    bookingType: "Online",
    bookingId: "OID001",
    addons: "Extra Towel",
    paymentMethod: "Card",
    amountPaid: "PHP 650",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 21,
    name: "Mark Villanueva",
    date: "15/03/2025",
    age: 29,
    gender: "Male",
    contact: "9198765432",
    bookingType: "Walk-in",
    bookingId: "WID080",
    addons: "Tent Rental",
    paymentMethod: "GCash",
    amountPaid: "PHP 2,800",
    premiumStatus: "Premium",
    status: "Cancelled",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "Schedule Conflict",
  },
  {
    id: 22,
    name: "Genevieve Simpson",
    date: "18/03/2025",
    age: 38,
    gender: "Male",
    contact: "1199446622",
    bookingType: "Online",
    bookingId: "OID073",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 890",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 23,
    name: "Claire Mason",
    date: "22/03/2025",
    age: 27,
    gender: "Male",
    contact: "4499227788",
    bookingType: "Online",
    bookingId: "OID049",
    addons: "City Tour",
    paymentMethod: "Card",
    amountPaid: "PHP 2,000",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 24,
    name: "Alexander Scott",
    date: "28/03/2025",
    age: 35,
    gender: "Male",
    contact: "1133557799",
    bookingType: "Online",
    bookingId: "OID013",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 900",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 25,
    name: "Evelyn Scott",
    date: "01/04/2025",
    age: 59,
    gender: "Female",
    contact: "9966113300",
    bookingType: "Walk-in",
    bookingId: "WID070",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,260",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 26,
    name: "Alejandro Perez",
    date: "03/04/2025",
    age: 55,
    gender: "Male",
    contact: "3344556677",
    bookingType: "Walk-in",
    bookingId: "WID010",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,350",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },

  {
    id: 27,
    name: "Diana Parker",
    date: "05/04/2025",
    age: 45,
    gender: "Female",
    contact: "8844772299",
    bookingType: "Walk-in",
    bookingId: "WID058",
    addons: "Extra Towel",
    paymentMethod: "Cash",
    amountPaid: "PHP 560",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 28,
    name: "Alyssa Lopez",
    date: "05/04/2025",
    age: 26,
    gender: "Female",
    contact: "9126547896",
    bookingType: "Online",
    bookingId: "OID081",
    addons: "Art Kit",
    paymentMethod: "Credit Card",
    amountPaid: "PHP 1,200",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 29,
    name: "Angel Carter",
    date: "12/04/2025",
    age: 51,
    gender: "Female",
    contact: "22446688",
    bookingType: "Walk-in",
    bookingId: "WID022",
    addons: "Parking",
    paymentMethod: "Cash",
    amountPaid: "PHP 580",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 30,
    name: "Brian Griffin",
    date: "19/04/2025",
    age: 44,
    gender: "Female",
    contact: "6600337744",
    bookingType: "Walk-in",
    bookingId: "WID034",
    addons: "",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,020",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 31,
    name: "Christopher Yu",
    date: "20/04/2025",
    age: 31,
    gender: "Male",
    contact: "9236547890",
    bookingType: "Walk-in",
    bookingId: "WID082",
    addons: "Clue Pack",
    paymentMethod: "Maya",
    amountPaid: "PHP 1,800",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 32,
    name: "Chloe Long",
    date: "26/04/2025",
    age: 53,
    gender: "Female",
    contact: "7722550011",
    bookingType: "Walk-in",
    bookingId: "WID046",
    addons: "Massage",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,450",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 33,
    name: "Amanda Wright",
    date: "02/05/2025",
    age: 40,
    gender: "Male",
    contact: "3355779911",
    bookingType: "Online",
    bookingId: "OID017",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 750",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 34,
    name: "Sofia Lim",
    date: "10/05/2025",
    age: 24,
    gender: "Female",
    contact: "9111223344",
    bookingType: "Online",
    bookingId: "OID083",
    addons: "Custom Book Selection",
    paymentMethod: "GCash",
    amountPaid: "PHP 1,500",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 35,
    name: "Caroline Johnson",
    date: "12/05/2025",
    age: 31,
    gender: "Male",
    contact: "5599226688",
    bookingType: "Online",
    bookingId: "OID041",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 660",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 36,
    name: "Angelo Reyes",
    date: "15/02/2025",
    age: 30,
    gender: "Male",
    contact: "9112233445",
    bookingType: "Walk-in",
    bookingId: "WID078",
    addons: "Transport Rental",
    paymentMethod: "GCash",
    amountPaid: "PHP 3,000",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 37,
    name: "Amy Allen",
    date: "18/02/2025",
    age: 62,
    gender: "Male",
    contact: "4466880022",
    bookingType: "Online",
    bookingId: "OID019",
    addons: "City Tour",
    paymentMethod: "Card",
    amountPaid: "PHP 1,900",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 38,
    name: "Avery Foster",
    date: "25/02/2025",
    age: 39,
    gender: "Male",
    contact: "5588114477",
    bookingType: "Online",
    bookingId: "OID031",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 630",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 39,
    name: "Eleanor Powell",
    date: "01/03/2025",
    age: 29,
    gender: "Male",
    contact: "5511449966",
    bookingType: "Online",
    bookingId: "OID061",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 690",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 40,
    name: "Trisha Gomez",
    date: "02/03/2025",
    age: 27,
    gender: "Female",
    contact: "9234567890",
    bookingType: "Online",
    bookingId: "OID079",
    addons: "Photographer, Car Rental",
    paymentMethod: "Maya",
    amountPaid: "PHP 3,500",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 41,
    name: "Anthony Cook",
    date: "05/03/2025",
    age: 26,
    gender: "Male",
    contact: "2255881144",
    bookingType: "Online",
    bookingId: "OID025",
    addons: "Dinner",
    paymentMethod: "Card",
    amountPaid: "PHP 1,700",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 42,
    name: "Cameron Howard",
    date: "10/03/2025",
    age: 28,
    gender: "Male",
    contact: "3377004466",
    bookingType: "Online",
    bookingId: "OID037",
    addons: "",
    paymentMethod: "Card",
    amountPaid: "PHP 780",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 43,
    name: "Aaliyah Brown",
    date: "15/03/2025",
    age: 32,
    gender: "Female",
    contact: "9876543210",
    bookingType: "Online",
    bookingId: "OID001",
    addons: "Extra Towel",
    paymentMethod: "Card",
    amountPaid: "PHP 650",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 44,
    name: "Mark Villanueva",
    date: "15/03/2025",
    age: 29,
    gender: "Male",
    contact: "9198765432",
    bookingType: "Walk-in",
    bookingId: "WID080",
    addons: "Tent Rental",
    paymentMethod: "GCash",
    amountPaid: "PHP 2,800",
    premiumStatus: "Premium",
    status: "Cancelled",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "Schedule Conflict",
  },
  {
    id: 45,
    name: "Genevieve Simpson",
    date: "18/03/2025",
    age: 38,
    gender: "Male",
    contact: "1199446622",
    bookingType: "Online",
    bookingId: "OID073",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 890",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 46,
    name: "Claire Mason",
    date: "22/03/2025",
    age: 27,
    gender: "Male",
    contact: "4499227788",
    bookingType: "Online",
    bookingId: "OID049",
    addons: "City Tour",
    paymentMethod: "Card",
    amountPaid: "PHP 2,000",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 47,
    name: "Alexander Scott",
    date: "28/03/2025",
    age: 35,
    gender: "Male",
    contact: "1133557799",
    bookingType: "Online",
    bookingId: "OID013",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 900",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 48,
    name: "Evelyn Scott",
    date: "01/04/2025",
    age: 59,
    gender: "Female",
    contact: "9966113300",
    bookingType: "Walk-in",
    bookingId: "WID070",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,260",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 49,
    name: "Addison Jackson",
    date: "18/05/2025",
    age: 21,
    gender: "Female",
    contact: "9988776655",
    bookingType: "Online",
    bookingId: "OID005",
    addons: "Parking",
    paymentMethod: "Card",
    amountPaid: "PHP 550",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 50,
    name: "Cooper Morgan",
    date: "22/05/2025",
    age: 21,
    gender: "Male",
    contact: "1177005522",
    bookingType: "Online",
    bookingId: "OID053",
    addons: "Breakfast",
    paymentMethod: "Card",
    amountPaid: "PHP 950",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 51,
    name: "Austin Edwards",
    date: "25/05/2025",
    age: 23,
    gender: "Male",
    contact: "4477003366",
    bookingType: "Online",
    bookingId: "OID029",
    addons: "City Tour",
    paymentMethod: "Card",
    amountPaid: "PHP 1,950",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 52,
    name: "Ellie Rivera",
    date: "27/05/2025",
    age: 35,
    gender: "Male",
    contact: "2299446633",
    bookingType: "Online",
    bookingId: "OID065",
    addons: "Dinner",
    paymentMethod: "Card",
    amountPaid: "PHP 1,720",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 53,
    name: "Benjamin Gray",
    date: "05/06/2025",
    age: 52,
    gender: "Female",
    contact: "33669922",
    bookingType: "Walk-in",
    bookingId: "WID032",
    addons: "Parking",
    paymentMethod: "Cash",
    amountPaid: "PHP 610",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 54,
    name: "Alan Martinez",
    date: "12/06/2025",
    age: 25,
    gender: "Male",
    contact: "2233445566",
    bookingType: "Walk-in",
    bookingId: "WID008",
    addons: "City Tour",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,800",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 55,
    name: "Declan Myers",
    date: "15/06/2025",
    age: 51,
    gender: "Female",
    contact: "7733661188",
    bookingType: "Walk-in",
    bookingId: "WID056",
    addons: "Massage",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,400",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 56,
    name: "Ethan Ross",
    date: "19/06/2025",
    age: 46,
    gender: "Female",
    contact: "8855002299",
    bookingType: "Walk-in",
    bookingId: "WID068",
    addons: "Extra Bed",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,180",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 57,
    name: "Gabriel Cruz",
    date: "22/06/2025",
    age: 27,
    gender: "Male",
    contact: "9345876123",
    bookingType: "Walk-in",
    bookingId: "WID084",
    addons: "Champagne",
    paymentMethod: "Credit Card",
    amountPaid: "PHP 5,000",
    premiumStatus: "Non Premium",
    status: "Pending",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 58,
    name: "Andrea Baker",
    date: "25/06/2025",
    age: 24,
    gender: "Female",
    contact: "9911335577",
    bookingType: "Walk-in",
    bookingId: "WID020",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,250",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 59,
    name: "Carl Hughes",
    date: "03/07/2025",
    age: 41,
    gender: "Female",
    contact: "8822559911",
    bookingType: "Walk-in",
    bookingId: "WID038",
    addons: "Extra Towel",
    paymentMethod: "Cash",
    amountPaid: "PHP 540",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 60,
    name: "Elias Price",
    date: "08/07/2025",
    age: 42,
    gender: "Female",
    contact: "66994411",
    bookingType: "Walk-in",
    bookingId: "WID062",
    addons: "Parking",
    paymentMethod: "Cash",
    amountPaid: "PHP 620",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 61,
    name: "Alexis Thomas",
    date: "09/07/2025",
    age: 22,
    gender: "Female",
    contact: "6688002244",
    bookingType: "Walk-in",
    bookingId: "WID014",
    addons: "",
    paymentMethod: "Cash",
    amountPaid: "PHP 500",
    premiumStatus: "Non Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 62,
    name: "April Cooper",
    date: "15/07/2025",
    age: 49,
    gender: "Female",
    contact: "7700336699",
    bookingType: "Walk-in",
    bookingId: "WID026",
    addons: "Massage",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,300",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 63,
    name: "Aaron Davis",
    date: "22/07/2025",
    age: 45,
    gender: "Male",
    contact: "1234567899",
    bookingType: "Walk-in",
    bookingId: "WID002",
    addons: "Massage",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,200",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 64,
    name: "George Smith",
    date: "25/07/2025",
    age: 50,
    gender: "Female",
    contact: "6644991177",
    bookingType: "Walk-in",
    bookingId: "WID074",
    addons: "",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,060",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },
  {
    id: 65,
    name: "Cody Miller",
    date: "29/07/2025",
    age: 49,
    gender: "Female",
    contact: "9944772233",
    bookingType: "Walk-in",
    bookingId: "WID050",
    addons: "Lunch",
    paymentMethod: "Cash",
    amountPaid: "PHP 1,330",
    premiumStatus: "Premium",
    status: "Completed",
    nextBooking: "",
    experience: "",
    time: "",
    cancellationReason: "",
  },















  { 
    id: 66, 
    name: "Christian Lopez", 
    date: "03/08/2025", 
    age: 29, 
    gender: "Male", 
    contact: "3388116677", 
    bookingType: "Online", 
    bookingId: "OID047", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 740", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 67, 
    name: "Gabriel Shaw", 
    date: "07/08/2025", 
    age: 20, 
    gender: "Male", 
    contact: "5522779966", 
    bookingType: "Online", 
    bookingId: "OID071", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 650", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 68, 
    name: "Dominic Perry", 
    date: "10/08/2025", 
    age: 32, 
    gender: "Male", 
    contact: "4400338855", 
    bookingType: "Online", 
    bookingId: "OID059", 
    addons: "Airport Transfer", 
    paymentMethod: "Card", 
    amountPaid: "PHP 2,050", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 69,
    name: "Daniel Cortez", 
    date: "12/08/2025", 
    age: 29, 
    gender: "Male", 
    contact: "9134567821", 
    bookingType: "Walk-in", 
    bookingId: "WID086", 
    addons: "Succulent Kit", 
    paymentMethod: "Maya", 
    amountPaid: "PHP 1,300", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 70, 
    name: "Alex Roberts", 
    date: "17/08/2025", 
    age: 29, 
    gender: "Female", 
    contact: "8899001122", 
    bookingType: "Online", 
    bookingId: "OID011", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 600", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 71, 
    name: "Angela Clark", 
    date: "20/08/2025", 
    age: 30, 
    gender: "Male", 
    contact: "1144770033", 
    bookingType: "Online", 
    bookingId: "OID023", 
    addons: "Breakfast", 
    paymentMethod: "Card", 
    amountPaid: "PHP 850", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 72, 
    name: "Ava Flores", 
    date: "02/09/2025", 
    age: 46, 
    gender: "Female", 
    contact: "9922558811", 
    bookingType: "Walk-in", 
    bookingId: "WID030", 
    addons: "Lunch", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 1,280", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 73, 
    name: "Emily Roberts", 
    date: "05/09/2025", 
    age: 52, 
    gender: "Female", 
    contact: "7744991188", 
    bookingType: "Walk-in", 
    bookingId: "WID066", 
    addons: "Massage", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 1,320", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 74, 
    name: "Amber Young", 
    date: "10/09/2025", 
    age: 27, 
    gender: "Female", 
    contact: "8800224466", 
    bookingType: "Walk-in", 
    bookingId: "WID018", 
    addons: "Extra Towel", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 520", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 75, 
    name: "Catherine Jones", 
    date: "18/09/2025", 
    age: 47, 
    gender: "Female", 
    contact: "44771133", 
    bookingType: "Walk-in", 
    bookingId: "WID042", 
    addons: "Parking", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 600", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 76, 
    name: "Adrian King", 
    date: "25/09/2025", 
    age: 50, 
    gender: "Male", 
    contact: "4455667788", 
    bookingType: "Walk-in", 
    bookingId: "WID006", 
    addons: "Dinner", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 1,500", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 77, 
    name: "Daniel Morris", 
    date: "29/09/2025", 
    age: 40, 
    gender: "Female", 
    contact: "6622550077", 
    bookingType: "Walk-in", 
    bookingId: "WID054", 
    addons: "", 
    paymentMethod: "Cash", 
    amountPaid: "PHP 1,080", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 78, 
    name: "Andrew Campbell", 
    date: "05/10/2025", 
    age: 37, 
    gender: "Male", 
    contact: "5577991133", 
    bookingType: "Online", 
    bookingId: "OID021", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 680", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 79, 
    name: "Brandon Green", 
    date: "12/10/2025", 
    age: 20, 
    gender: "Male", 
    contact: "1155882299", 
    bookingType: "Online", 
    bookingId: "OID033", 
    addons: "Breakfast", 
    paymentMethod: "Card", 
    amountPaid: "PHP 880", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 80, 
    name: "Chelsea Lewis", 
    date: "15/10/2025", 
    age: 34, 
    gender: "Male", 
    contact: "2277005566", 
    bookingType: "Online", 
    bookingId: "OID045", 
    addons: "Dinner", 
    paymentMethod: "Card", 
    amountPaid: "PHP 1,750", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 81, 
    name: "Justin Tan", 
    date: "18/10/2025", 
    age: 28, 
    gender: "Male", 
    contact: "9198765432", 
    bookingType: "Walk-in", 
    bookingId: "WID088", 
    addons: "VIP Booth", 
    paymentMethod: "GCash", 
    amountPaid: "PHP 2,500", 
    premiumStatus: "Non Premium", 
    status: "Cancelled", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 82, 
    name: "Eva Sanders", 
    date: "26/10/2025", 
    age: 31, 
    gender: "Male", 
    contact: "4411668855", 
    bookingType: "Online", 
    bookingId: "OID069", 
    addons: "City Tour", 
    paymentMethod: "Card", 
    amountPaid: "PHP 1,980", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 83, 
    name: "Albert Nelson", 
    date: "30/10/2025", 
    age: 41, 
    gender: "Female", 
    contact: "7788990011", 
    bookingType: "Online", 
    bookingId: "OID009", 
    addons: "Extra Bed", 
    paymentMethod: "Card", 
    amountPaid: "PHP 1,100", 
    premiumStatus: "Non Premium", 
    status: "Cancelled", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 84, 
    name: "Abigail Garcia", 
    date: "01/11/2025", 
    age: 28, 
    gender: "Male", 
    contact: "5551234567", 
    bookingType: "Online", 
    bookingId: "OID003", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 800", 
    premiumStatus: "Non Premium", 
    status: "Cancelled", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 85, 
    name: "Grace Stewart", 
    date: "01/11/2025", 
    age: 27, 
    gender: "Male", 
    contact: "2200557733", 
    bookingType: "Online", 
    bookingId: "OID075", 
    addons: "Dinner", 
    paymentMethod: "Card", 
    amountPaid: "PHP 1,740", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 86, 
    name: "Cole Mitchell", 
    date: "05/11/2025", 
    age: 30, 
    gender: "Male", 
    contact: "5500338899", 
    bookingType: "Online", 
    bookingId: "OID051", 
    addons: "", 
    paymentMethod: "Card", 
    amountPaid: "PHP 700", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 87, 
    name: "Carlos James", 
    date: "08/11/2025", 
    age: 25, 
    gender: "Male", 
    contact: "4488115577", 
    bookingType: "Online", 
    bookingId: "OID039", 
    addons: "Airport Transfer", 
    paymentMethod: "Card", 
    amountPaid: "PHP 2,100", 
    premiumStatus: "Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 88, 
    name: "Katrina Ortega", 
    date: "09/11/2025", 
    age: 27, 
    gender: "Female", 
    contact: "9256723489", 
    bookingType: "Online", 
    bookingId: "OID089", 
    addons: "Art Guide", 
    paymentMethod: "Credit Card", 
    amountPaid: "PHP 1,800", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },
  { 
    id: 89, 
    name: "Elizabeth Reed", 
    date: "12/11/2025", 
    age: 26, 
    gender: "Male", 
    contact: "1188225577", 
    bookingType: "Online", 
    bookingId: "OID063", 
    addons: "Breakfast", 
    paymentMethod: "Card", 
    amountPaid: "PHP 910", 
    premiumStatus: "Non Premium", 
    status: "Completed", 
    nextBooking: "", 
    experience: "", 
    time: "", 
    cancellationReason: "", 
  },

];

export default recentCustomers;
